{{- $fullName := include "common.fullname" . -}}
{{- if .Values.services.clusterIP }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.services.nodePort }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-np
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.port }}
      nodePort: {{ .Values.nodePort }}
      name: http
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
{{- end }}